// Code generated by scripts/color_gen.py. DO NOT EDIT.
package gocolor

// Color contains all 16 colors listed in https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN#text-formatting
type Color struct {

	// BgBlack - Applies non-bold/bright black to background
	BgBlack string

	// BgBlackBright - Applies bold/bright black to background
	BgBlackBright string

	// BgBlue - Applies non-bold/bright blue to background
	BgBlue string

	// BgBlueBright - Applies bold/bright blue to background
	BgBlueBright string

	// BgCyan - Applies non-bold/bright cyan to background
	BgCyan string

	// BgCyanBright - Applies bold/bright cyan to background
	BgCyanBright string

	// BgDefault - Applies only the background portion of the defaults (see 0)
	BgDefault string

	// BgExtended - Applies extended color value to the background (see details below)
	BgExtended string

	// BgGreen - Applies non-bold/bright green to background
	BgGreen string

	// BgGreenBright - Applies bold/bright green to background
	BgGreenBright string

	// BgMagenta - Applies non-bold/bright magenta to background
	BgMagenta string

	// BgMagentaBright - Applies bold/bright magenta to background
	BgMagentaBright string

	// BgRed - Applies non-bold/bright red to background
	BgRed string

	// BgRedBright - Applies bold/bright red to background
	BgRedBright string

	// BgWhite - Applies non-bold/bright white to background
	BgWhite string

	// BgWhiteBright - Applies bold/bright white to background
	BgWhiteBright string

	// BgYellow - Applies non-bold/bright yellow to background
	BgYellow string

	// BgYellowBright - Applies bold/bright yellow to background
	BgYellowBright string

	// Bold - Applies brightness/intensity flag to foreground color
	Bold string

	// Default - Returns all attributes to the default state prior to modification
	Default string

	// FgBlack - Applies non-bold/bright black to foreground
	FgBlack string

	// FgBlackBright - Applies bold/bright black to foreground
	FgBlackBright string

	// FgBlue - Applies non-bold/bright blue to foreground
	FgBlue string

	// FgBlueBright - Applies bold/bright blue to foreground
	FgBlueBright string

	// FgCyan - Applies non-bold/bright cyan to foreground
	FgCyan string

	// FgCyanBright - Applies bold/bright cyan to foreground
	FgCyanBright string

	// FgDefault - Applies only the foreground portion of the defaults (see 0)
	FgDefault string

	// FgExtended - Applies extended color value to the foreground (see details below)
	FgExtended string

	// FgGreen - Applies non-bold/bright green to foreground
	FgGreen string

	// FgGreenBright - Applies bold/bright green to foreground
	FgGreenBright string

	// FgMagenta - Applies non-bold/bright magenta to foreground
	FgMagenta string

	// FgMagentaBright - Applies bold/bright magenta to foreground
	FgMagentaBright string

	// FgRed - Applies non-bold/bright red to foreground
	FgRed string

	// FgRedBright - Applies bold/bright red to foreground
	FgRedBright string

	// FgWhite - Applies non-bold/bright white to foreground
	FgWhite string

	// FgWhiteBright - Applies bold/bright white to foreground
	FgWhiteBright string

	// FgYellow - Applies non-bold/bright yellow to foreground
	FgYellow string

	// FgYellowBright - Applies bold/bright yellow to foreground
	FgYellowBright string

	// Negative - Swaps foreground and background colors
	Negative string

	// Nobold - Removes brightness/intensity flag from foreground color
	Nobold string

	// Nounderline - Removes underline
	Nounderline string

	// Positive - Returns foreground/background to normal
	Positive string

	// Underline - Adds underline
	Underline string

}

// Disable sets all colors to the empty string, effectivly disabling color output
func (c *Color) Disable() {
	c.BgBlack = ""
	c.BgBlackBright = ""
	c.BgBlue = ""
	c.BgBlueBright = ""
	c.BgCyan = ""
	c.BgCyanBright = ""
	c.BgDefault = ""
	c.BgExtended = ""
	c.BgGreen = ""
	c.BgGreenBright = ""
	c.BgMagenta = ""
	c.BgMagentaBright = ""
	c.BgRed = ""
	c.BgRedBright = ""
	c.BgWhite = ""
	c.BgWhiteBright = ""
	c.BgYellow = ""
	c.BgYellowBright = ""
	c.Bold = ""
	c.Default = ""
	c.FgBlack = ""
	c.FgBlackBright = ""
	c.FgBlue = ""
	c.FgBlueBright = ""
	c.FgCyan = ""
	c.FgCyanBright = ""
	c.FgDefault = ""
	c.FgExtended = ""
	c.FgGreen = ""
	c.FgGreenBright = ""
	c.FgMagenta = ""
	c.FgMagentaBright = ""
	c.FgRed = ""
	c.FgRedBright = ""
	c.FgWhite = ""
	c.FgWhiteBright = ""
	c.FgYellow = ""
	c.FgYellowBright = ""
	c.Negative = ""
	c.Nobold = ""
	c.Nounderline = ""
	c.Positive = ""
	c.Underline = ""
}

// Enable sets all colors to their color codes
func (c *Color) Enable() {
	c.BgBlack = "\033[40m"
	c.BgBlackBright = "\033[100m"
	c.BgBlue = "\033[44m"
	c.BgBlueBright = "\033[104m"
	c.BgCyan = "\033[46m"
	c.BgCyanBright = "\033[106m"
	c.BgDefault = "\033[49m"
	c.BgExtended = "\033[48m"
	c.BgGreen = "\033[42m"
	c.BgGreenBright = "\033[102m"
	c.BgMagenta = "\033[45m"
	c.BgMagentaBright = "\033[105m"
	c.BgRed = "\033[41m"
	c.BgRedBright = "\033[101m"
	c.BgWhite = "\033[47m"
	c.BgWhiteBright = "\033[107m"
	c.BgYellow = "\033[43m"
	c.BgYellowBright = "\033[103m"
	c.Bold = "\033[1m"
	c.Default = "\033[0m"
	c.FgBlack = "\033[30m"
	c.FgBlackBright = "\033[90m"
	c.FgBlue = "\033[34m"
	c.FgBlueBright = "\033[94m"
	c.FgCyan = "\033[36m"
	c.FgCyanBright = "\033[96m"
	c.FgDefault = "\033[39m"
	c.FgExtended = "\033[38m"
	c.FgGreen = "\033[32m"
	c.FgGreenBright = "\033[92m"
	c.FgMagenta = "\033[35m"
	c.FgMagentaBright = "\033[95m"
	c.FgRed = "\033[31m"
	c.FgRedBright = "\033[91m"
	c.FgWhite = "\033[37m"
	c.FgWhiteBright = "\033[97m"
	c.FgYellow = "\033[33m"
	c.FgYellowBright = "\033[93m"
	c.Negative = "\033[7m"
	c.Nobold = "\033[22m"
	c.Nounderline = "\033[24m"
	c.Positive = "\033[27m"
	c.Underline = "\033[4m"
}

