// Code generated by scripts/color_gen.py. DO NOT EDIT.
package gocolor

const (
	BgBlack Code = "\033[40m" // Applies non-bold/bright black to background
	BgBlackBright Code = "\033[100m" // Applies bold/bright black to background
	BgBlue Code = "\033[44m" // Applies non-bold/bright blue to background
	BgBlueBright Code = "\033[104m" // Applies bold/bright blue to background
	BgCyan Code = "\033[46m" // Applies non-bold/bright cyan to background
	BgCyanBright Code = "\033[106m" // Applies bold/bright cyan to background
	BgDefault Code = "\033[49m" // Applies only the background portion of the defaults (see 0)
	BgExtended Code = "\033[48m" // Applies extended color value to the background (see details below)
	BgGreen Code = "\033[42m" // Applies non-bold/bright green to background
	BgGreenBright Code = "\033[102m" // Applies bold/bright green to background
	BgMagenta Code = "\033[45m" // Applies non-bold/bright magenta to background
	BgMagentaBright Code = "\033[105m" // Applies bold/bright magenta to background
	BgRed Code = "\033[41m" // Applies non-bold/bright red to background
	BgRedBright Code = "\033[101m" // Applies bold/bright red to background
	BgWhite Code = "\033[47m" // Applies non-bold/bright white to background
	BgWhiteBright Code = "\033[107m" // Applies bold/bright white to background
	BgYellow Code = "\033[43m" // Applies non-bold/bright yellow to background
	BgYellowBright Code = "\033[103m" // Applies bold/bright yellow to background
	Bold Code = "\033[1m" // Applies brightness/intensity flag to foreground color
	Default Code = "\033[0m" // Returns all attributes to the default state prior to modification
	FgBlack Code = "\033[30m" // Applies non-bold/bright black to foreground
	FgBlackBright Code = "\033[90m" // Applies bold/bright black to foreground
	FgBlue Code = "\033[34m" // Applies non-bold/bright blue to foreground
	FgBlueBright Code = "\033[94m" // Applies bold/bright blue to foreground
	FgCyan Code = "\033[36m" // Applies non-bold/bright cyan to foreground
	FgCyanBright Code = "\033[96m" // Applies bold/bright cyan to foreground
	FgDefault Code = "\033[39m" // Applies only the foreground portion of the defaults (see 0)
	FgExtended Code = "\033[38m" // Applies extended color value to the foreground (see details below)
	FgGreen Code = "\033[32m" // Applies non-bold/bright green to foreground
	FgGreenBright Code = "\033[92m" // Applies bold/bright green to foreground
	FgMagenta Code = "\033[35m" // Applies non-bold/bright magenta to foreground
	FgMagentaBright Code = "\033[95m" // Applies bold/bright magenta to foreground
	FgRed Code = "\033[31m" // Applies non-bold/bright red to foreground
	FgRedBright Code = "\033[91m" // Applies bold/bright red to foreground
	FgWhite Code = "\033[37m" // Applies non-bold/bright white to foreground
	FgWhiteBright Code = "\033[97m" // Applies bold/bright white to foreground
	FgYellow Code = "\033[33m" // Applies non-bold/bright yellow to foreground
	FgYellowBright Code = "\033[93m" // Applies bold/bright yellow to foreground
	Negative Code = "\033[7m" // Swaps foreground and background colors
	Nobold Code = "\033[22m" // Removes brightness/intensity flag from foreground color
	Nounderline Code = "\033[24m" // Removes underline
	Positive Code = "\033[27m" // Returns foreground/background to normal
	Underline Code = "\033[4m" // Adds underline
)

// Color contains all colors listed in https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN#text-formatting . It can be enabled or disabled
type Color struct {
	BgBlack Code // Applies non-bold/bright black to background
	BgBlackBright Code // Applies bold/bright black to background
	BgBlue Code // Applies non-bold/bright blue to background
	BgBlueBright Code // Applies bold/bright blue to background
	BgCyan Code // Applies non-bold/bright cyan to background
	BgCyanBright Code // Applies bold/bright cyan to background
	BgDefault Code // Applies only the background portion of the defaults (see 0)
	BgExtended Code // Applies extended color value to the background (see details below)
	BgGreen Code // Applies non-bold/bright green to background
	BgGreenBright Code // Applies bold/bright green to background
	BgMagenta Code // Applies non-bold/bright magenta to background
	BgMagentaBright Code // Applies bold/bright magenta to background
	BgRed Code // Applies non-bold/bright red to background
	BgRedBright Code // Applies bold/bright red to background
	BgWhite Code // Applies non-bold/bright white to background
	BgWhiteBright Code // Applies bold/bright white to background
	BgYellow Code // Applies non-bold/bright yellow to background
	BgYellowBright Code // Applies bold/bright yellow to background
	Bold Code // Applies brightness/intensity flag to foreground color
	Default Code // Returns all attributes to the default state prior to modification
	FgBlack Code // Applies non-bold/bright black to foreground
	FgBlackBright Code // Applies bold/bright black to foreground
	FgBlue Code // Applies non-bold/bright blue to foreground
	FgBlueBright Code // Applies bold/bright blue to foreground
	FgCyan Code // Applies non-bold/bright cyan to foreground
	FgCyanBright Code // Applies bold/bright cyan to foreground
	FgDefault Code // Applies only the foreground portion of the defaults (see 0)
	FgExtended Code // Applies extended color value to the foreground (see details below)
	FgGreen Code // Applies non-bold/bright green to foreground
	FgGreenBright Code // Applies bold/bright green to foreground
	FgMagenta Code // Applies non-bold/bright magenta to foreground
	FgMagentaBright Code // Applies bold/bright magenta to foreground
	FgRed Code // Applies non-bold/bright red to foreground
	FgRedBright Code // Applies bold/bright red to foreground
	FgWhite Code // Applies non-bold/bright white to foreground
	FgWhiteBright Code // Applies bold/bright white to foreground
	FgYellow Code // Applies non-bold/bright yellow to foreground
	FgYellowBright Code // Applies bold/bright yellow to foreground
	Negative Code // Swaps foreground and background colors
	Nobold Code // Removes brightness/intensity flag from foreground color
	Nounderline Code // Removes underline
	Positive Code // Returns foreground/background to normal
	Underline Code // Adds underline
}

// DisableAll sets all colors to the empty string, effectively disabling color output
func (c *Color) DisableAll() {
	c.BgBlack = Empty
	c.BgBlackBright = Empty
	c.BgBlue = Empty
	c.BgBlueBright = Empty
	c.BgCyan = Empty
	c.BgCyanBright = Empty
	c.BgDefault = Empty
	c.BgExtended = Empty
	c.BgGreen = Empty
	c.BgGreenBright = Empty
	c.BgMagenta = Empty
	c.BgMagentaBright = Empty
	c.BgRed = Empty
	c.BgRedBright = Empty
	c.BgWhite = Empty
	c.BgWhiteBright = Empty
	c.BgYellow = Empty
	c.BgYellowBright = Empty
	c.Bold = Empty
	c.Default = Empty
	c.FgBlack = Empty
	c.FgBlackBright = Empty
	c.FgBlue = Empty
	c.FgBlueBright = Empty
	c.FgCyan = Empty
	c.FgCyanBright = Empty
	c.FgDefault = Empty
	c.FgExtended = Empty
	c.FgGreen = Empty
	c.FgGreenBright = Empty
	c.FgMagenta = Empty
	c.FgMagentaBright = Empty
	c.FgRed = Empty
	c.FgRedBright = Empty
	c.FgWhite = Empty
	c.FgWhiteBright = Empty
	c.FgYellow = Empty
	c.FgYellowBright = Empty
	c.Negative = Empty
	c.Nobold = Empty
	c.Nounderline = Empty
	c.Positive = Empty
	c.Underline = Empty
}

// EnableAll sets all colors to their color codes
func (c *Color) EnableAll() {
	c.BgBlack = BgBlack
	c.BgBlackBright = BgBlackBright
	c.BgBlue = BgBlue
	c.BgBlueBright = BgBlueBright
	c.BgCyan = BgCyan
	c.BgCyanBright = BgCyanBright
	c.BgDefault = BgDefault
	c.BgExtended = BgExtended
	c.BgGreen = BgGreen
	c.BgGreenBright = BgGreenBright
	c.BgMagenta = BgMagenta
	c.BgMagentaBright = BgMagentaBright
	c.BgRed = BgRed
	c.BgRedBright = BgRedBright
	c.BgWhite = BgWhite
	c.BgWhiteBright = BgWhiteBright
	c.BgYellow = BgYellow
	c.BgYellowBright = BgYellowBright
	c.Bold = Bold
	c.Default = Default
	c.FgBlack = FgBlack
	c.FgBlackBright = FgBlackBright
	c.FgBlue = FgBlue
	c.FgBlueBright = FgBlueBright
	c.FgCyan = FgCyan
	c.FgCyanBright = FgCyanBright
	c.FgDefault = FgDefault
	c.FgExtended = FgExtended
	c.FgGreen = FgGreen
	c.FgGreenBright = FgGreenBright
	c.FgMagenta = FgMagenta
	c.FgMagentaBright = FgMagentaBright
	c.FgRed = FgRed
	c.FgRedBright = FgRedBright
	c.FgWhite = FgWhite
	c.FgWhiteBright = FgWhiteBright
	c.FgYellow = FgYellow
	c.FgYellowBright = FgYellowBright
	c.Negative = Negative
	c.Nobold = Nobold
	c.Nounderline = Nounderline
	c.Positive = Positive
	c.Underline = Underline
}

